### ISSUE TITLE
symmetry prefactor 0 and wrong symmetry

### ISSUE THREAD

**Issue by whzhangg** [ttadano/alamode#11]
Dear Tadano-san:

it seems that the symmetry is wrong for my system for fitting the harmonic IFC:
(I listed the IFC for the same pair from both phonopy and alamode)

atom1-atom1 is related by symmetry to atom217-atom217
The IFC for atom1 - atom1 agrees between phonopy and alamode 
but for the atom217 - atom217 they do not agree. the symmetry do not correspond as well with a prefactor 0 (which should be +-1 if I understand correctly ): 

#####################################

-----the force constant of ifc from phonopy extraction:
atom1 - atom1
[[ 0.10404742  0.00036116  0.00023593]
 [ 0.00036116  0.1761779  -0.02505608]
 [ 0.00023593 -0.02505608  0.08803488]]
atom 217 - atom 217
[[ 0.10404742 -0.00036116  0.00023593]
 [-0.00036116  0.1761779   0.02505608]
 [ 0.00023593  0.02505608  0.08803488]]

 -----FC from alamode fcs (first 6):
  FC2_1    4   1.0408208e-01
    1     1.00000    1x    1x
    2     1.00000  217x  217x
    3     0.00000  217x  217y
    4     0.00000  217y  217x

  FC2_2    5   3.6100860e-04
    1     1.00000    1x    1y
    2     1.00000    1y    1x
    3    -0.00000  217x  217z         << x-z 
    4    -0.00000  217y  217y         << y-y
    5    -0.00000  217z  217x         << z-x

  FC2_3    4   2.3738387e-04
    1     1.00000    1x    1z
    2     1.00000    1z    1x
    3     0.00000  217y  217z
    4     0.00000  217z  217y

  FC2_4    1   1.7591016e-01
    1     1.00000    1y    1y

  FC2_5    3  -2.4996065e-02
    1     1.00000    1y    1z
    2     1.00000    1z    1y
    3    -0.00000  217z  217z

  FC2_6    1   8.7708402e-02
    1     1.00000    1z    1z

**Comment by ttadano** [comment]
That is strange behavior. It might be a bug. Could you give me the alamode input files?

**Comment by whzhangg** [comment]
Thank you for the reply.
I uploaded the related files to
https://github.com/whzhangg/alamode_calculation.git

the cell information can be found in the "conventional_information" file.

**Comment by ttadano** [comment]
The strange behavior occurs because of the small non-zero elements in the cell parameters.
In your ``&cell`` field, you set
```
&cell
  1.88972688      # factor in Bohr unit
  26.251044216   0.000000006   0.372037422
   0.000000004  16.734988796   0.000000003
  -0.394369128   0.000000004  27.354852538
/
```
The small values at a12, a21, a23, and a32 are numerical noises and they should be zero. However, ALM treats them as signals and uses them when generating an irreducible set of force constants by using symmetry. The problem solved when I changed the ``&cell`` field as
```
&cell
  1.88972688      # factor in Bohr unit
  26.251044216   0.000000000   0.372037422
   0.000000000  16.734988796   0.000000000
  -0.394369128   0.000000000  27.354852538
/
```

This fix also improves the fitting error because the symmetry is correctly handled. With the original input, the fitting error is ~30%. With the fixed ``&cell`` field, it becomes ~7.7%.

To avoid errors related to symmetrization, I recommend using the following procedure:
1. Symmetrize the primitive lattice by using ``spglib`` or any other alternatives
2. Create a supercell from the symmetrized primitive lattice by multiplying a transformation_matrix. Print enough numerical digits, say 15, both for the lattice parameters and fractional coordinates of atoms.
3. Run ALM with the generated supercell 

I always follow the above procedure, but for better user experience, I've recently updated ALM so that it becomes more robust against the numerical noises in the ``&cell`` field. The new version is available on this repository (develop branch). 

In the new version, force constants are symmetrized in the fractional coordinate (``FC_BASIS = Fractional``, default) instead of the Cartesian coordinate (``FC_BASIS = Cartesian``). If you want, you can change the symmetrization basis via the ``FC_BASIS`` tag in the ``&general`` field. 

I've tested the new version with your original ``&cell`` field and found that it works nicely and gives the fitting error of ~7.7%. When ``FC_BASIS = Fractional``, the force constants in  the ``PREFIX.fcs`` are given in the fractional coordinate. So, the meaning of the ``xyz`` components, for example,  in ``1x 1x`` or ``217z 217z`` are not the Cartesian any more.

Anyway, if the input crystal structure is well symmetrized, ``FC_BASIS`` value does not affect the final result (e.g. phonon frequency, thermal conductivity).

**Comment by whzhangg** [comment]
Thank you for the reply.

If I understand correctly, the fractional directional force constant can be transformed back to cartesian force constant by multiplying the fractional FC on the left: 
[[a1,b1,c1]
 [a2,b2,c2]
 [a3,b3,c3]] 
[a1,a2,a3]... are the unit vector of the primitive cell lattice.

Is it right? because I do want to analysis the force constant in the future.

**Comment by whzhangg** [comment]
Tadano-san, I also find some compile issue in the developer alamode, when compiling 'alm', I have:

`constraint.cpp(1920): error #140: too many arguments in function call
              get_value_from_xml(pt, "Data.ForceConstants.CubicUnique.Basis", 0));`

They are caused because by **constraint.cpp** line 1920 and 1902:

`get_value_from_xml(pt, "Data.ForceConstants.HarmonicUnique.Basis", 0));`

 
It seems that **get_value_from_xml** only take two parameter. After I remove the third parameter at that two places I compile successfully.

**Comment by ttadano** [comment]
``get_value_from_xml`` can take third optional variable as implemented in https://github.com/ttadano/alamode/blob/28b20a31cf84b4be92cc26c2cfbcc2ff948735b5/include/xml_parser.h#L18

Did you also update this file as well?

**Comment by ttadano** [comment]
Regarding the conversion of force constant basis, you need to multiply the matrix N times for Nth-order force constants. I've uploaded a short note on the basis conversion at 
https://github.com/ttadano/alamode/blob/gh-pages/files/force_constant.pdf
In ALM, we normalize the conversion matrix C so that det(C) becomes 1.

If you want to get force constants in Cartesian coordinate, I would recommend using ALM API for python available at https://github.com/ttadano/ALM. The installation note and examples of ALM are shown in https://alm.readthedocs.io/en/develop/.

The following script can generate second-order force constants for all pairs inside the supercell:
```python
from alm import ALM
import numpy as np

lavec = [[  26.251044216,   0.000000006,   0.372037422],
         [   0.000000004,  16.734988796,   0.000000003],
         [  -0.394369128,   0.000000004,  27.354852538]]

xcoord = np.loadtxt('position.dat', usecols=[1,2,3])
kd_types = np.loadtxt('position.dat', usecols=[0,])
kd_nums = {1:49, 2:52}
kd = np.array([kd_nums[i] for i in kd_types[:]])

nat = len(xcoord)
dfset = np.loadtxt("DFSET_harmonic")
disp = dfset[:,:3].reshape((-1, nat, 3))
force = dfset[:,3:].reshape((-1, nat, 3))

# alm.alm_new() and alm.alm_delete() are done by 'with' statement
with ALM(lavec, xcoord, kd) as alm:
    # alm.set_verbosity(1)
    alm.define(1)
    alm.displacements = disp
    alm.forces = force
    info = alm.optimize(solver='SimplicialLDLT')
    fc_values, elem_indices = alm.get_fc(1, mode='all')
    c = "xyz"
    for (fc, elem) in zip(fc_values, elem_indices):
        v1 = elem[0] // 3
        c1 = elem[0] % 3
        v2 = elem[1] // 3
        c2 = elem[1] % 3
        print("%f %d%s %d%s" % ((fc, v1 + 1, c[c1], v2 + 1, c[c2])))
```

**Comment by whzhangg** [comment]
I have now correctly fit the FC and I will try to use the python tool.

Thank you for you time and help to solve my problem (and also to develop this code).
