### ISSUE TITLE
Huge difference between Phonopy and Alamode for slab

### ISSUE THREAD

**Issue by m-a-saleh** [ttadano/alamode#176]
Dear developers,

I have a Si slab "structure attached" for which I need to calculate second-order force constants. For finite difference displacements and supercell size of 2x4x1, Phonopy produces 40 supercell displacements, while alamode produces 50 supercell displacements (input file attached).

Phonopy gives what seems to be the correct dispersion:
![phonopy-dispersion](https://github.com/ttadano/alamode/assets/87962486/51cf200f-c6ce-4585-941c-39a8a18e0447)

I did not calculate the dispersion using the 50 displacements of alamode. However, when I use alamode to generate DFSET from the 40 displacements produced by Phonopy and calculate the dispersion, I obtain the following:

![alamode-dispersion](https://github.com/ttadano/alamode/assets/87962486/540fbc60-54e3-4b90-904e-133bb4438148)

For both Phonopy and alamode, I dont specify cut-off pair.

Attachments:
[slabPOSCAR.txt](https://github.com/ttadano/alamode/files/14717835/slabPOSCAR.txt)
[Alm_harm.in.txt](https://github.com/ttadano/alamode/files/14718038/Alm_harm.in.txt)

**Comment by ttadano** [comment]
One possible reason for this is inconsistency in the atomic orders in `&position` and `DFSET` converted from the phonopy data.

**Comment by m-a-saleh** [comment]
> One possible reason for this is inconsistency in the atomic orders in `&position` and `DFSET` converted from the phonopy data.

This was actually the reason. Thanks, Dr. Tadano.

However, after calculating the dispersion with the 50 displacements suggested by alamode, I got the following dispersion with a 26% fitting error:
![alamode-dispersion-3](https://github.com/ttadano/alamode/assets/87962486/924f8303-7682-4fc2-9aac-95f4b316885a)

Another point: for me, it is counter-intuitive that alamode needs more displacements than Phonopy since it is based on fitting.

**Comment by ttadano** [comment]
Hi. The new result looks more consistent with phonopy. I would suggest that you use the primitive cell lattice parameters for the `&cell` field of anphon, if you didn't.

The smaller number of displacements suggested by phonopy is probably because their algorithm is more sophisticated and uses more information about the space group symmetries than the ALAMODE implementation.

**Comment by m-a-saleh** [comment]
Thanks, Dr. Tadano
Now it is perfect
![alamode-dispersion4](https://github.com/ttadano/alamode/assets/87962486/c7a455e0-a482-469d-aa3c-cb6817cd825b)

However, I still do not know why the fitting error is big (26%) despite the OK dispersion.

Another point regarding the number of displacements, for a 1x2x1 supercell to calculate the third order force constants, the situation is reversed: Phonon3py generates ~8000 displacements, while alamode generates ~4000 displacements (`&cutoff *-* None None /`). Is this OK?

**Comment by ttadano** [comment]
The large fitting error is probably due to the residual atomic forces in the perfect supercell (no displacements). This can be easily tested by removing the residual forces following https://alamode.readthedocs.io/en/latest/faq.html.

Even if there are non-zero residual forces, the accuracy of the harmonic IFCs is not affected by this. However, the non-zero residual forces influence the accuracy of higher-order force constants, so I recommend that you subtract the offset force components from the training data following the instruction in the webpage above.

About the number of displacements for the cubic term, I'm not sure what makes that difference between phonopy and alamode. Anyways, I recommend that you use the compressive sensing approach instead of the systematic displacement method for extracting 3- and higher-order force constants.

**Comment by m-a-saleh** [comment]
> The large fitting error is probably due to the residual atomic forces in the perfect supercell (no displacements). This can be easily tested by removing the residual forces following https://alamode.readthedocs.io/en/latest/faq.html.
> 
This reduced the error to 10%. Thanks Dr. Tadano
